[package]
name = "proto-gen"
version = "0.1.0"
edition = "2024"

[dependencies]
prost = { version = "0.14.1", features = ["derive"] }
serde = "1.0.228"

[build-dependencies]
prost-build = { version = "0.14.1", default-features = false }
